# Generated by Django 3.0.5 on 2020-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegranteSq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresq', models.CharField(max_length=100)),
                ('cedulasq', models.BigIntegerField(max_length=100, unique=True)),
                ('programasq', models.CharField(max_length=100)),
                ('condicionsq', models.CharField(max_length=100)),
                ('telefonosq', models.BigIntegerField(max_length=100)),
                ('emailsq', models.CharField(max_length=100)),
                ('dificultadsq', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Integrantes',
            },
        ),
    ]
