# Generated by Django 3.0.5 on 2020-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutsalMas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='nombreequipo',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
