# Generated by Django 3.0.5 on 2020-04-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutsalMas', '0002_integrante_nombreequipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrante',
            name='nombreequipo',
        ),
    ]
