# Generated by Django 3.0.5 on 2020-04-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutsalMas', '0004_integrante_nombreequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='programa',
            field=models.CharField(max_length=100),
        ),
    ]
