# Generated by Django 3.0.5 on 2020-04-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegranteA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrea', models.CharField(max_length=100)),
                ('cedulaa', models.BigIntegerField(max_length=100, unique=True)),
                ('programaa', models.CharField(max_length=100)),
                ('condiciona', models.CharField(max_length=100)),
                ('telefonoa', models.BigIntegerField(max_length=100)),
                ('emaila', models.CharField(max_length=100)),
                ('dificultada', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Integrantes',
            },
        ),
    ]
