# Generated by Django 3.0.5 on 2020-04-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegranteBF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrebf', models.CharField(max_length=100)),
                ('cedulabf', models.BigIntegerField(max_length=100, unique=True)),
                ('programabf', models.CharField(max_length=100)),
                ('condicionbf', models.CharField(max_length=100)),
                ('telefonobf', models.BigIntegerField(max_length=100)),
                ('emailbf', models.CharField(max_length=100)),
                ('nombreequipobf', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Integrantes',
            },
        ),
    ]
